---

- hosts: all
  become: true
  tasks:

  - name: Repository index
    dnf:
      update_cache: yes

  - name: install apache httpd packages
    dnf:
      name: httpd
      state: absent
  - name: add php support for apache
    dnf:
      name: php-gd,php-ldap,php-odbc,php-pear,php-snmp,php-soap,curl,curl-devel
      state: absent
